// Code generated by ent, DO NOT EDIT.

package session

import (
	"shareserver/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldID, id))
}

// AdminID applies equality check predicate on the "admin_id" field. It's identical to AdminIDEQ.
func AdminID(v int64) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldAdminID, v))
}

// Csrf applies equality check predicate on the "csrf" field. It's identical to CsrfEQ.
func Csrf(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCsrf, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCreatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldExpiresAt, v))
}

// AdminIDEQ applies the EQ predicate on the "admin_id" field.
func AdminIDEQ(v int64) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldAdminID, v))
}

// AdminIDNEQ applies the NEQ predicate on the "admin_id" field.
func AdminIDNEQ(v int64) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldAdminID, v))
}

// AdminIDIn applies the In predicate on the "admin_id" field.
func AdminIDIn(vs ...int64) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldAdminID, vs...))
}

// AdminIDNotIn applies the NotIn predicate on the "admin_id" field.
func AdminIDNotIn(vs ...int64) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldAdminID, vs...))
}

// AdminIDGT applies the GT predicate on the "admin_id" field.
func AdminIDGT(v int64) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldAdminID, v))
}

// AdminIDGTE applies the GTE predicate on the "admin_id" field.
func AdminIDGTE(v int64) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldAdminID, v))
}

// AdminIDLT applies the LT predicate on the "admin_id" field.
func AdminIDLT(v int64) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldAdminID, v))
}

// AdminIDLTE applies the LTE predicate on the "admin_id" field.
func AdminIDLTE(v int64) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldAdminID, v))
}

// AdminIDIsNil applies the IsNil predicate on the "admin_id" field.
func AdminIDIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldAdminID))
}

// AdminIDNotNil applies the NotNil predicate on the "admin_id" field.
func AdminIDNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldAdminID))
}

// CsrfEQ applies the EQ predicate on the "csrf" field.
func CsrfEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCsrf, v))
}

// CsrfNEQ applies the NEQ predicate on the "csrf" field.
func CsrfNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldCsrf, v))
}

// CsrfIn applies the In predicate on the "csrf" field.
func CsrfIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldCsrf, vs...))
}

// CsrfNotIn applies the NotIn predicate on the "csrf" field.
func CsrfNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldCsrf, vs...))
}

// CsrfGT applies the GT predicate on the "csrf" field.
func CsrfGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldCsrf, v))
}

// CsrfGTE applies the GTE predicate on the "csrf" field.
func CsrfGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldCsrf, v))
}

// CsrfLT applies the LT predicate on the "csrf" field.
func CsrfLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldCsrf, v))
}

// CsrfLTE applies the LTE predicate on the "csrf" field.
func CsrfLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldCsrf, v))
}

// CsrfContains applies the Contains predicate on the "csrf" field.
func CsrfContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldCsrf, v))
}

// CsrfHasPrefix applies the HasPrefix predicate on the "csrf" field.
func CsrfHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldCsrf, v))
}

// CsrfHasSuffix applies the HasSuffix predicate on the "csrf" field.
func CsrfHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldCsrf, v))
}

// CsrfEqualFold applies the EqualFold predicate on the "csrf" field.
func CsrfEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldCsrf, v))
}

// CsrfContainsFold applies the ContainsFold predicate on the "csrf" field.
func CsrfContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldCsrf, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtContains applies the Contains predicate on the "created_at" field.
func CreatedAtContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldCreatedAt, v))
}

// CreatedAtHasPrefix applies the HasPrefix predicate on the "created_at" field.
func CreatedAtHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldCreatedAt, v))
}

// CreatedAtHasSuffix applies the HasSuffix predicate on the "created_at" field.
func CreatedAtHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldCreatedAt, v))
}

// CreatedAtEqualFold applies the EqualFold predicate on the "created_at" field.
func CreatedAtEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldCreatedAt, v))
}

// CreatedAtContainsFold applies the ContainsFold predicate on the "created_at" field.
func CreatedAtContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldCreatedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtContains applies the Contains predicate on the "expires_at" field.
func ExpiresAtContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldExpiresAt, v))
}

// ExpiresAtHasPrefix applies the HasPrefix predicate on the "expires_at" field.
func ExpiresAtHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldExpiresAt, v))
}

// ExpiresAtHasSuffix applies the HasSuffix predicate on the "expires_at" field.
func ExpiresAtHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldExpiresAt, v))
}

// ExpiresAtEqualFold applies the EqualFold predicate on the "expires_at" field.
func ExpiresAtEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldExpiresAt, v))
}

// ExpiresAtContainsFold applies the ContainsFold predicate on the "expires_at" field.
func ExpiresAtContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldExpiresAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Session) predicate.Session {
	return predicate.Session(sql.NotPredicates(p))
}
