// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdminsColumns holds the columns for the "admins" table.
	AdminsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeString},
	}
	// AdminsTable holds the schema information for the "admins" table.
	AdminsTable = &schema.Table{
		Name:       "admins",
		Columns:    AdminsColumns,
		PrimaryKey: []*schema.Column{AdminsColumns[0]},
	}
	// AuditEventsColumns holds the columns for the "audit_events" table.
	AuditEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "actor", Type: field.TypeString},
		{Name: "ip", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "target", Type: field.TypeString},
		{Name: "meta", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeString},
	}
	// AuditEventsTable holds the schema information for the "audit_events" table.
	AuditEventsTable = &schema.Table{
		Name:       "audit_events",
		Columns:    AuditEventsColumns,
		PrimaryKey: []*schema.Column{AuditEventsColumns[0]},
	}
	// IPBansColumns holds the columns for the "ip_bans" table.
	IPBansColumns = []*schema.Column{
		{Name: "ip", Type: field.TypeString},
		{Name: "banned_until", Type: field.TypeString},
	}
	// IPBansTable holds the schema information for the "ip_bans" table.
	IPBansTable = &schema.Table{
		Name:       "ip_bans",
		Columns:    IPBansColumns,
		PrimaryKey: []*schema.Column{IPBansColumns[0]},
	}
	// LoginFailureEventsColumns holds the columns for the "login_failure_events" table.
	LoginFailureEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ip", Type: field.TypeString},
		{Name: "happened_at", Type: field.TypeString},
	}
	// LoginFailureEventsTable holds the schema information for the "login_failure_events" table.
	LoginFailureEventsTable = &schema.Table{
		Name:       "login_failure_events",
		Columns:    LoginFailureEventsColumns,
		PrimaryKey: []*schema.Column{LoginFailureEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "loginfailureevent_ip",
				Unique:  false,
				Columns: []*schema.Column{LoginFailureEventsColumns[1]},
			},
			{
				Name:    "loginfailureevent_happened_at",
				Unique:  false,
				Columns: []*schema.Column{LoginFailureEventsColumns[2]},
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "admin_id", Type: field.TypeInt64, Nullable: true},
		{Name: "csrf", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeString},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "session_expires_at",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[4]},
			},
		},
	}
	// SharesColumns holds the columns for the "shares" table.
	SharesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "visibility", Type: field.TypeString},
		{Name: "private_key_hash", Type: field.TypeString, Nullable: true},
		{Name: "encrypted", Type: field.TypeBool},
		{Name: "cipher_meta", Type: field.TypeString, Nullable: true},
		{Name: "zip_manifest", Type: field.TypeString, Nullable: true},
		{Name: "size", Type: field.TypeInt64},
		{Name: "blob_path", Type: field.TypeString},
		{Name: "blob_sha256", Type: field.TypeString},
		{Name: "uploader_ip", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeString},
		{Name: "purged_at", Type: field.TypeString, Nullable: true},
	}
	// SharesTable holds the schema information for the "shares" table.
	SharesTable = &schema.Table{
		Name:       "shares",
		Columns:    SharesColumns,
		PrimaryKey: []*schema.Column{SharesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "share_visibility",
				Unique:  false,
				Columns: []*schema.Column{SharesColumns[2]},
			},
			{
				Name:    "share_private_key_hash",
				Unique:  false,
				Columns: []*schema.Column{SharesColumns[3]},
			},
			{
				Name:    "share_expires_at",
				Unique:  false,
				Columns: []*schema.Column{SharesColumns[11]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdminsTable,
		AuditEventsTable,
		IPBansTable,
		LoginFailureEventsTable,
		SessionsTable,
		SharesTable,
	}
)

func init() {
}
