// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"shareserver/internal/ent/ipban"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// IpBan is the model entity for the IpBan schema.
type IpBan struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// BannedUntil holds the value of the "banned_until" field.
	BannedUntil  string `json:"banned_until,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IpBan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ipban.FieldID, ipban.FieldBannedUntil:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IpBan fields.
func (_m *IpBan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ipban.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case ipban.FieldBannedUntil:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field banned_until", values[i])
			} else if value.Valid {
				_m.BannedUntil = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IpBan.
// This includes values selected through modifiers, order, etc.
func (_m *IpBan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IpBan.
// Note that you need to call IpBan.Unwrap() before calling this method if this IpBan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IpBan) Update() *IpBanUpdateOne {
	return NewIpBanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IpBan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IpBan) Unwrap() *IpBan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IpBan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IpBan) String() string {
	var builder strings.Builder
	builder.WriteString("IpBan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("banned_until=")
	builder.WriteString(_m.BannedUntil)
	builder.WriteByte(')')
	return builder.String()
}

// IpBans is a parsable slice of IpBan.
type IpBans []*IpBan
