// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shareserver/internal/ent/ipban"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IpBanCreate is the builder for creating a IpBan entity.
type IpBanCreate struct {
	config
	mutation *IpBanMutation
	hooks    []Hook
}

// SetBannedUntil sets the "banned_until" field.
func (_c *IpBanCreate) SetBannedUntil(v string) *IpBanCreate {
	_c.mutation.SetBannedUntil(v)
	return _c
}

// SetID sets the "id" field.
func (_c *IpBanCreate) SetID(v string) *IpBanCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the IpBanMutation object of the builder.
func (_c *IpBanCreate) Mutation() *IpBanMutation {
	return _c.mutation
}

// Save creates the IpBan in the database.
func (_c *IpBanCreate) Save(ctx context.Context) (*IpBan, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IpBanCreate) SaveX(ctx context.Context) *IpBan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IpBanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IpBanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IpBanCreate) check() error {
	if _, ok := _c.mutation.BannedUntil(); !ok {
		return &ValidationError{Name: "banned_until", err: errors.New(`ent: missing required field "IpBan.banned_until"`)}
	}
	return nil
}

func (_c *IpBanCreate) sqlSave(ctx context.Context) (*IpBan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected IpBan.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IpBanCreate) createSpec() (*IpBan, *sqlgraph.CreateSpec) {
	var (
		_node = &IpBan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ipban.Table, sqlgraph.NewFieldSpec(ipban.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.BannedUntil(); ok {
		_spec.SetField(ipban.FieldBannedUntil, field.TypeString, value)
		_node.BannedUntil = value
	}
	return _node, _spec
}

// IpBanCreateBulk is the builder for creating many IpBan entities in bulk.
type IpBanCreateBulk struct {
	config
	err      error
	builders []*IpBanCreate
}

// Save creates the IpBan entities in the database.
func (_c *IpBanCreateBulk) Save(ctx context.Context) ([]*IpBan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IpBan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IpBanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IpBanCreateBulk) SaveX(ctx context.Context) []*IpBan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IpBanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IpBanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
