// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shareserver/internal/ent/ipban"
	"shareserver/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IpBanUpdate is the builder for updating IpBan entities.
type IpBanUpdate struct {
	config
	hooks    []Hook
	mutation *IpBanMutation
}

// Where appends a list predicates to the IpBanUpdate builder.
func (_u *IpBanUpdate) Where(ps ...predicate.IpBan) *IpBanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBannedUntil sets the "banned_until" field.
func (_u *IpBanUpdate) SetBannedUntil(v string) *IpBanUpdate {
	_u.mutation.SetBannedUntil(v)
	return _u
}

// SetNillableBannedUntil sets the "banned_until" field if the given value is not nil.
func (_u *IpBanUpdate) SetNillableBannedUntil(v *string) *IpBanUpdate {
	if v != nil {
		_u.SetBannedUntil(*v)
	}
	return _u
}

// Mutation returns the IpBanMutation object of the builder.
func (_u *IpBanUpdate) Mutation() *IpBanMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IpBanUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IpBanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IpBanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IpBanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *IpBanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(ipban.Table, ipban.Columns, sqlgraph.NewFieldSpec(ipban.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BannedUntil(); ok {
		_spec.SetField(ipban.FieldBannedUntil, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ipban.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IpBanUpdateOne is the builder for updating a single IpBan entity.
type IpBanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IpBanMutation
}

// SetBannedUntil sets the "banned_until" field.
func (_u *IpBanUpdateOne) SetBannedUntil(v string) *IpBanUpdateOne {
	_u.mutation.SetBannedUntil(v)
	return _u
}

// SetNillableBannedUntil sets the "banned_until" field if the given value is not nil.
func (_u *IpBanUpdateOne) SetNillableBannedUntil(v *string) *IpBanUpdateOne {
	if v != nil {
		_u.SetBannedUntil(*v)
	}
	return _u
}

// Mutation returns the IpBanMutation object of the builder.
func (_u *IpBanUpdateOne) Mutation() *IpBanMutation {
	return _u.mutation
}

// Where appends a list predicates to the IpBanUpdate builder.
func (_u *IpBanUpdateOne) Where(ps ...predicate.IpBan) *IpBanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IpBanUpdateOne) Select(field string, fields ...string) *IpBanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IpBan entity.
func (_u *IpBanUpdateOne) Save(ctx context.Context) (*IpBan, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IpBanUpdateOne) SaveX(ctx context.Context) *IpBan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IpBanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IpBanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *IpBanUpdateOne) sqlSave(ctx context.Context) (_node *IpBan, err error) {
	_spec := sqlgraph.NewUpdateSpec(ipban.Table, ipban.Columns, sqlgraph.NewFieldSpec(ipban.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IpBan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ipban.FieldID)
		for _, f := range fields {
			if !ipban.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ipban.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BannedUntil(); ok {
		_spec.SetField(ipban.FieldBannedUntil, field.TypeString, value)
	}
	_node = &IpBan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ipban.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
