// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shareserver/internal/ent/loginfailureevent"
	"shareserver/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoginFailureEventUpdate is the builder for updating LoginFailureEvent entities.
type LoginFailureEventUpdate struct {
	config
	hooks    []Hook
	mutation *LoginFailureEventMutation
}

// Where appends a list predicates to the LoginFailureEventUpdate builder.
func (_u *LoginFailureEventUpdate) Where(ps ...predicate.LoginFailureEvent) *LoginFailureEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIP sets the "ip" field.
func (_u *LoginFailureEventUpdate) SetIP(v string) *LoginFailureEventUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *LoginFailureEventUpdate) SetNillableIP(v *string) *LoginFailureEventUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetHappenedAt sets the "happened_at" field.
func (_u *LoginFailureEventUpdate) SetHappenedAt(v string) *LoginFailureEventUpdate {
	_u.mutation.SetHappenedAt(v)
	return _u
}

// SetNillableHappenedAt sets the "happened_at" field if the given value is not nil.
func (_u *LoginFailureEventUpdate) SetNillableHappenedAt(v *string) *LoginFailureEventUpdate {
	if v != nil {
		_u.SetHappenedAt(*v)
	}
	return _u
}

// Mutation returns the LoginFailureEventMutation object of the builder.
func (_u *LoginFailureEventUpdate) Mutation() *LoginFailureEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LoginFailureEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginFailureEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LoginFailureEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginFailureEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LoginFailureEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(loginfailureevent.Table, loginfailureevent.Columns, sqlgraph.NewFieldSpec(loginfailureevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(loginfailureevent.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.HappenedAt(); ok {
		_spec.SetField(loginfailureevent.FieldHappenedAt, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginfailureevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LoginFailureEventUpdateOne is the builder for updating a single LoginFailureEvent entity.
type LoginFailureEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LoginFailureEventMutation
}

// SetIP sets the "ip" field.
func (_u *LoginFailureEventUpdateOne) SetIP(v string) *LoginFailureEventUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *LoginFailureEventUpdateOne) SetNillableIP(v *string) *LoginFailureEventUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetHappenedAt sets the "happened_at" field.
func (_u *LoginFailureEventUpdateOne) SetHappenedAt(v string) *LoginFailureEventUpdateOne {
	_u.mutation.SetHappenedAt(v)
	return _u
}

// SetNillableHappenedAt sets the "happened_at" field if the given value is not nil.
func (_u *LoginFailureEventUpdateOne) SetNillableHappenedAt(v *string) *LoginFailureEventUpdateOne {
	if v != nil {
		_u.SetHappenedAt(*v)
	}
	return _u
}

// Mutation returns the LoginFailureEventMutation object of the builder.
func (_u *LoginFailureEventUpdateOne) Mutation() *LoginFailureEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the LoginFailureEventUpdate builder.
func (_u *LoginFailureEventUpdateOne) Where(ps ...predicate.LoginFailureEvent) *LoginFailureEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LoginFailureEventUpdateOne) Select(field string, fields ...string) *LoginFailureEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LoginFailureEvent entity.
func (_u *LoginFailureEventUpdateOne) Save(ctx context.Context) (*LoginFailureEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginFailureEventUpdateOne) SaveX(ctx context.Context) *LoginFailureEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LoginFailureEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginFailureEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LoginFailureEventUpdateOne) sqlSave(ctx context.Context) (_node *LoginFailureEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(loginfailureevent.Table, loginfailureevent.Columns, sqlgraph.NewFieldSpec(loginfailureevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LoginFailureEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loginfailureevent.FieldID)
		for _, f := range fields {
			if !loginfailureevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != loginfailureevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(loginfailureevent.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.HappenedAt(); ok {
		_spec.SetField(loginfailureevent.FieldHappenedAt, field.TypeString, value)
	}
	_node = &LoginFailureEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginfailureevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
