// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"shareserver/internal/ent/loginfailureevent"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// LoginFailureEvent is the model entity for the LoginFailureEvent schema.
type LoginFailureEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// IP holds the value of the "ip" field.
	IP string `json:"ip,omitempty"`
	// HappenedAt holds the value of the "happened_at" field.
	HappenedAt   string `json:"happened_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LoginFailureEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case loginfailureevent.FieldID:
			values[i] = new(sql.NullInt64)
		case loginfailureevent.FieldIP, loginfailureevent.FieldHappenedAt:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LoginFailureEvent fields.
func (_m *LoginFailureEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case loginfailureevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case loginfailureevent.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case loginfailureevent.FieldHappenedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field happened_at", values[i])
			} else if value.Valid {
				_m.HappenedAt = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LoginFailureEvent.
// This includes values selected through modifiers, order, etc.
func (_m *LoginFailureEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LoginFailureEvent.
// Note that you need to call LoginFailureEvent.Unwrap() before calling this method if this LoginFailureEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LoginFailureEvent) Update() *LoginFailureEventUpdateOne {
	return NewLoginFailureEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LoginFailureEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LoginFailureEvent) Unwrap() *LoginFailureEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LoginFailureEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LoginFailureEvent) String() string {
	var builder strings.Builder
	builder.WriteString("LoginFailureEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteString(", ")
	builder.WriteString("happened_at=")
	builder.WriteString(_m.HappenedAt)
	builder.WriteByte(')')
	return builder.String()
}

// LoginFailureEvents is a parsable slice of LoginFailureEvent.
type LoginFailureEvents []*LoginFailureEvent
