// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shareserver/internal/ent/predicate"
	"shareserver/internal/ent/share"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShareUpdate is the builder for updating Share entities.
type ShareUpdate struct {
	config
	hooks    []Hook
	mutation *ShareMutation
}

// Where appends a list predicates to the ShareUpdate builder.
func (_u *ShareUpdate) Where(ps ...predicate.Share) *ShareUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ShareUpdate) SetTitle(v string) *ShareUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableTitle(v *string) *ShareUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *ShareUpdate) SetVisibility(v string) *ShareUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableVisibility(v *string) *ShareUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetPrivateKeyHash sets the "private_key_hash" field.
func (_u *ShareUpdate) SetPrivateKeyHash(v string) *ShareUpdate {
	_u.mutation.SetPrivateKeyHash(v)
	return _u
}

// SetNillablePrivateKeyHash sets the "private_key_hash" field if the given value is not nil.
func (_u *ShareUpdate) SetNillablePrivateKeyHash(v *string) *ShareUpdate {
	if v != nil {
		_u.SetPrivateKeyHash(*v)
	}
	return _u
}

// ClearPrivateKeyHash clears the value of the "private_key_hash" field.
func (_u *ShareUpdate) ClearPrivateKeyHash() *ShareUpdate {
	_u.mutation.ClearPrivateKeyHash()
	return _u
}

// SetEncrypted sets the "encrypted" field.
func (_u *ShareUpdate) SetEncrypted(v bool) *ShareUpdate {
	_u.mutation.SetEncrypted(v)
	return _u
}

// SetNillableEncrypted sets the "encrypted" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableEncrypted(v *bool) *ShareUpdate {
	if v != nil {
		_u.SetEncrypted(*v)
	}
	return _u
}

// SetCipherMeta sets the "cipher_meta" field.
func (_u *ShareUpdate) SetCipherMeta(v string) *ShareUpdate {
	_u.mutation.SetCipherMeta(v)
	return _u
}

// SetNillableCipherMeta sets the "cipher_meta" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableCipherMeta(v *string) *ShareUpdate {
	if v != nil {
		_u.SetCipherMeta(*v)
	}
	return _u
}

// ClearCipherMeta clears the value of the "cipher_meta" field.
func (_u *ShareUpdate) ClearCipherMeta() *ShareUpdate {
	_u.mutation.ClearCipherMeta()
	return _u
}

// SetZipManifest sets the "zip_manifest" field.
func (_u *ShareUpdate) SetZipManifest(v string) *ShareUpdate {
	_u.mutation.SetZipManifest(v)
	return _u
}

// SetNillableZipManifest sets the "zip_manifest" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableZipManifest(v *string) *ShareUpdate {
	if v != nil {
		_u.SetZipManifest(*v)
	}
	return _u
}

// ClearZipManifest clears the value of the "zip_manifest" field.
func (_u *ShareUpdate) ClearZipManifest() *ShareUpdate {
	_u.mutation.ClearZipManifest()
	return _u
}

// SetSize sets the "size" field.
func (_u *ShareUpdate) SetSize(v int64) *ShareUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableSize(v *int64) *ShareUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *ShareUpdate) AddSize(v int64) *ShareUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetBlobPath sets the "blob_path" field.
func (_u *ShareUpdate) SetBlobPath(v string) *ShareUpdate {
	_u.mutation.SetBlobPath(v)
	return _u
}

// SetNillableBlobPath sets the "blob_path" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableBlobPath(v *string) *ShareUpdate {
	if v != nil {
		_u.SetBlobPath(*v)
	}
	return _u
}

// SetBlobSha256 sets the "blob_sha256" field.
func (_u *ShareUpdate) SetBlobSha256(v string) *ShareUpdate {
	_u.mutation.SetBlobSha256(v)
	return _u
}

// SetNillableBlobSha256 sets the "blob_sha256" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableBlobSha256(v *string) *ShareUpdate {
	if v != nil {
		_u.SetBlobSha256(*v)
	}
	return _u
}

// SetUploaderIP sets the "uploader_ip" field.
func (_u *ShareUpdate) SetUploaderIP(v string) *ShareUpdate {
	_u.mutation.SetUploaderIP(v)
	return _u
}

// SetNillableUploaderIP sets the "uploader_ip" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableUploaderIP(v *string) *ShareUpdate {
	if v != nil {
		_u.SetUploaderIP(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ShareUpdate) SetExpiresAt(v string) *ShareUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableExpiresAt(v *string) *ShareUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ShareUpdate) ClearExpiresAt() *ShareUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ShareUpdate) SetCreatedAt(v string) *ShareUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ShareUpdate) SetNillableCreatedAt(v *string) *ShareUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetPurgedAt sets the "purged_at" field.
func (_u *ShareUpdate) SetPurgedAt(v string) *ShareUpdate {
	_u.mutation.SetPurgedAt(v)
	return _u
}

// SetNillablePurgedAt sets the "purged_at" field if the given value is not nil.
func (_u *ShareUpdate) SetNillablePurgedAt(v *string) *ShareUpdate {
	if v != nil {
		_u.SetPurgedAt(*v)
	}
	return _u
}

// ClearPurgedAt clears the value of the "purged_at" field.
func (_u *ShareUpdate) ClearPurgedAt() *ShareUpdate {
	_u.mutation.ClearPurgedAt()
	return _u
}

// Mutation returns the ShareMutation object of the builder.
func (_u *ShareUpdate) Mutation() *ShareMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ShareUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShareUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ShareUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShareUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ShareUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(share.Table, share.Columns, sqlgraph.NewFieldSpec(share.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(share.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(share.FieldVisibility, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrivateKeyHash(); ok {
		_spec.SetField(share.FieldPrivateKeyHash, field.TypeString, value)
	}
	if _u.mutation.PrivateKeyHashCleared() {
		_spec.ClearField(share.FieldPrivateKeyHash, field.TypeString)
	}
	if value, ok := _u.mutation.Encrypted(); ok {
		_spec.SetField(share.FieldEncrypted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CipherMeta(); ok {
		_spec.SetField(share.FieldCipherMeta, field.TypeString, value)
	}
	if _u.mutation.CipherMetaCleared() {
		_spec.ClearField(share.FieldCipherMeta, field.TypeString)
	}
	if value, ok := _u.mutation.ZipManifest(); ok {
		_spec.SetField(share.FieldZipManifest, field.TypeString, value)
	}
	if _u.mutation.ZipManifestCleared() {
		_spec.ClearField(share.FieldZipManifest, field.TypeString)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(share.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(share.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BlobPath(); ok {
		_spec.SetField(share.FieldBlobPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.BlobSha256(); ok {
		_spec.SetField(share.FieldBlobSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.UploaderIP(); ok {
		_spec.SetField(share.FieldUploaderIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(share.FieldExpiresAt, field.TypeString, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(share.FieldExpiresAt, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(share.FieldCreatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.PurgedAt(); ok {
		_spec.SetField(share.FieldPurgedAt, field.TypeString, value)
	}
	if _u.mutation.PurgedAtCleared() {
		_spec.ClearField(share.FieldPurgedAt, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{share.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ShareUpdateOne is the builder for updating a single Share entity.
type ShareUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ShareMutation
}

// SetTitle sets the "title" field.
func (_u *ShareUpdateOne) SetTitle(v string) *ShareUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableTitle(v *string) *ShareUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *ShareUpdateOne) SetVisibility(v string) *ShareUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableVisibility(v *string) *ShareUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetPrivateKeyHash sets the "private_key_hash" field.
func (_u *ShareUpdateOne) SetPrivateKeyHash(v string) *ShareUpdateOne {
	_u.mutation.SetPrivateKeyHash(v)
	return _u
}

// SetNillablePrivateKeyHash sets the "private_key_hash" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillablePrivateKeyHash(v *string) *ShareUpdateOne {
	if v != nil {
		_u.SetPrivateKeyHash(*v)
	}
	return _u
}

// ClearPrivateKeyHash clears the value of the "private_key_hash" field.
func (_u *ShareUpdateOne) ClearPrivateKeyHash() *ShareUpdateOne {
	_u.mutation.ClearPrivateKeyHash()
	return _u
}

// SetEncrypted sets the "encrypted" field.
func (_u *ShareUpdateOne) SetEncrypted(v bool) *ShareUpdateOne {
	_u.mutation.SetEncrypted(v)
	return _u
}

// SetNillableEncrypted sets the "encrypted" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableEncrypted(v *bool) *ShareUpdateOne {
	if v != nil {
		_u.SetEncrypted(*v)
	}
	return _u
}

// SetCipherMeta sets the "cipher_meta" field.
func (_u *ShareUpdateOne) SetCipherMeta(v string) *ShareUpdateOne {
	_u.mutation.SetCipherMeta(v)
	return _u
}

// SetNillableCipherMeta sets the "cipher_meta" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableCipherMeta(v *string) *ShareUpdateOne {
	if v != nil {
		_u.SetCipherMeta(*v)
	}
	return _u
}

// ClearCipherMeta clears the value of the "cipher_meta" field.
func (_u *ShareUpdateOne) ClearCipherMeta() *ShareUpdateOne {
	_u.mutation.ClearCipherMeta()
	return _u
}

// SetZipManifest sets the "zip_manifest" field.
func (_u *ShareUpdateOne) SetZipManifest(v string) *ShareUpdateOne {
	_u.mutation.SetZipManifest(v)
	return _u
}

// SetNillableZipManifest sets the "zip_manifest" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableZipManifest(v *string) *ShareUpdateOne {
	if v != nil {
		_u.SetZipManifest(*v)
	}
	return _u
}

// ClearZipManifest clears the value of the "zip_manifest" field.
func (_u *ShareUpdateOne) ClearZipManifest() *ShareUpdateOne {
	_u.mutation.ClearZipManifest()
	return _u
}

// SetSize sets the "size" field.
func (_u *ShareUpdateOne) SetSize(v int64) *ShareUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableSize(v *int64) *ShareUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *ShareUpdateOne) AddSize(v int64) *ShareUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetBlobPath sets the "blob_path" field.
func (_u *ShareUpdateOne) SetBlobPath(v string) *ShareUpdateOne {
	_u.mutation.SetBlobPath(v)
	return _u
}

// SetNillableBlobPath sets the "blob_path" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableBlobPath(v *string) *ShareUpdateOne {
	if v != nil {
		_u.SetBlobPath(*v)
	}
	return _u
}

// SetBlobSha256 sets the "blob_sha256" field.
func (_u *ShareUpdateOne) SetBlobSha256(v string) *ShareUpdateOne {
	_u.mutation.SetBlobSha256(v)
	return _u
}

// SetNillableBlobSha256 sets the "blob_sha256" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableBlobSha256(v *string) *ShareUpdateOne {
	if v != nil {
		_u.SetBlobSha256(*v)
	}
	return _u
}

// SetUploaderIP sets the "uploader_ip" field.
func (_u *ShareUpdateOne) SetUploaderIP(v string) *ShareUpdateOne {
	_u.mutation.SetUploaderIP(v)
	return _u
}

// SetNillableUploaderIP sets the "uploader_ip" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableUploaderIP(v *string) *ShareUpdateOne {
	if v != nil {
		_u.SetUploaderIP(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ShareUpdateOne) SetExpiresAt(v string) *ShareUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableExpiresAt(v *string) *ShareUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ShareUpdateOne) ClearExpiresAt() *ShareUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ShareUpdateOne) SetCreatedAt(v string) *ShareUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillableCreatedAt(v *string) *ShareUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetPurgedAt sets the "purged_at" field.
func (_u *ShareUpdateOne) SetPurgedAt(v string) *ShareUpdateOne {
	_u.mutation.SetPurgedAt(v)
	return _u
}

// SetNillablePurgedAt sets the "purged_at" field if the given value is not nil.
func (_u *ShareUpdateOne) SetNillablePurgedAt(v *string) *ShareUpdateOne {
	if v != nil {
		_u.SetPurgedAt(*v)
	}
	return _u
}

// ClearPurgedAt clears the value of the "purged_at" field.
func (_u *ShareUpdateOne) ClearPurgedAt() *ShareUpdateOne {
	_u.mutation.ClearPurgedAt()
	return _u
}

// Mutation returns the ShareMutation object of the builder.
func (_u *ShareUpdateOne) Mutation() *ShareMutation {
	return _u.mutation
}

// Where appends a list predicates to the ShareUpdate builder.
func (_u *ShareUpdateOne) Where(ps ...predicate.Share) *ShareUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ShareUpdateOne) Select(field string, fields ...string) *ShareUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Share entity.
func (_u *ShareUpdateOne) Save(ctx context.Context) (*Share, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShareUpdateOne) SaveX(ctx context.Context) *Share {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ShareUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShareUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ShareUpdateOne) sqlSave(ctx context.Context) (_node *Share, err error) {
	_spec := sqlgraph.NewUpdateSpec(share.Table, share.Columns, sqlgraph.NewFieldSpec(share.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Share.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, share.FieldID)
		for _, f := range fields {
			if !share.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != share.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(share.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(share.FieldVisibility, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrivateKeyHash(); ok {
		_spec.SetField(share.FieldPrivateKeyHash, field.TypeString, value)
	}
	if _u.mutation.PrivateKeyHashCleared() {
		_spec.ClearField(share.FieldPrivateKeyHash, field.TypeString)
	}
	if value, ok := _u.mutation.Encrypted(); ok {
		_spec.SetField(share.FieldEncrypted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CipherMeta(); ok {
		_spec.SetField(share.FieldCipherMeta, field.TypeString, value)
	}
	if _u.mutation.CipherMetaCleared() {
		_spec.ClearField(share.FieldCipherMeta, field.TypeString)
	}
	if value, ok := _u.mutation.ZipManifest(); ok {
		_spec.SetField(share.FieldZipManifest, field.TypeString, value)
	}
	if _u.mutation.ZipManifestCleared() {
		_spec.ClearField(share.FieldZipManifest, field.TypeString)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(share.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(share.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BlobPath(); ok {
		_spec.SetField(share.FieldBlobPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.BlobSha256(); ok {
		_spec.SetField(share.FieldBlobSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.UploaderIP(); ok {
		_spec.SetField(share.FieldUploaderIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(share.FieldExpiresAt, field.TypeString, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(share.FieldExpiresAt, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(share.FieldCreatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.PurgedAt(); ok {
		_spec.SetField(share.FieldPurgedAt, field.TypeString, value)
	}
	if _u.mutation.PurgedAtCleared() {
		_spec.ClearField(share.FieldPurgedAt, field.TypeString)
	}
	_node = &Share{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{share.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
