// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"shareserver/internal/ent/share"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShareCreate is the builder for creating a Share entity.
type ShareCreate struct {
	config
	mutation *ShareMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *ShareCreate) SetTitle(v string) *ShareCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetVisibility sets the "visibility" field.
func (_c *ShareCreate) SetVisibility(v string) *ShareCreate {
	_c.mutation.SetVisibility(v)
	return _c
}

// SetPrivateKeyHash sets the "private_key_hash" field.
func (_c *ShareCreate) SetPrivateKeyHash(v string) *ShareCreate {
	_c.mutation.SetPrivateKeyHash(v)
	return _c
}

// SetNillablePrivateKeyHash sets the "private_key_hash" field if the given value is not nil.
func (_c *ShareCreate) SetNillablePrivateKeyHash(v *string) *ShareCreate {
	if v != nil {
		_c.SetPrivateKeyHash(*v)
	}
	return _c
}

// SetEncrypted sets the "encrypted" field.
func (_c *ShareCreate) SetEncrypted(v bool) *ShareCreate {
	_c.mutation.SetEncrypted(v)
	return _c
}

// SetCipherMeta sets the "cipher_meta" field.
func (_c *ShareCreate) SetCipherMeta(v string) *ShareCreate {
	_c.mutation.SetCipherMeta(v)
	return _c
}

// SetNillableCipherMeta sets the "cipher_meta" field if the given value is not nil.
func (_c *ShareCreate) SetNillableCipherMeta(v *string) *ShareCreate {
	if v != nil {
		_c.SetCipherMeta(*v)
	}
	return _c
}

// SetZipManifest sets the "zip_manifest" field.
func (_c *ShareCreate) SetZipManifest(v string) *ShareCreate {
	_c.mutation.SetZipManifest(v)
	return _c
}

// SetNillableZipManifest sets the "zip_manifest" field if the given value is not nil.
func (_c *ShareCreate) SetNillableZipManifest(v *string) *ShareCreate {
	if v != nil {
		_c.SetZipManifest(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *ShareCreate) SetSize(v int64) *ShareCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetBlobPath sets the "blob_path" field.
func (_c *ShareCreate) SetBlobPath(v string) *ShareCreate {
	_c.mutation.SetBlobPath(v)
	return _c
}

// SetBlobSha256 sets the "blob_sha256" field.
func (_c *ShareCreate) SetBlobSha256(v string) *ShareCreate {
	_c.mutation.SetBlobSha256(v)
	return _c
}

// SetUploaderIP sets the "uploader_ip" field.
func (_c *ShareCreate) SetUploaderIP(v string) *ShareCreate {
	_c.mutation.SetUploaderIP(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ShareCreate) SetExpiresAt(v string) *ShareCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ShareCreate) SetNillableExpiresAt(v *string) *ShareCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ShareCreate) SetCreatedAt(v string) *ShareCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetPurgedAt sets the "purged_at" field.
func (_c *ShareCreate) SetPurgedAt(v string) *ShareCreate {
	_c.mutation.SetPurgedAt(v)
	return _c
}

// SetNillablePurgedAt sets the "purged_at" field if the given value is not nil.
func (_c *ShareCreate) SetNillablePurgedAt(v *string) *ShareCreate {
	if v != nil {
		_c.SetPurgedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ShareCreate) SetID(v string) *ShareCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ShareMutation object of the builder.
func (_c *ShareCreate) Mutation() *ShareMutation {
	return _c.mutation
}

// Save creates the Share in the database.
func (_c *ShareCreate) Save(ctx context.Context) (*Share, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShareCreate) SaveX(ctx context.Context) *Share {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShareCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShareCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShareCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Share.title"`)}
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`ent: missing required field "Share.visibility"`)}
	}
	if _, ok := _c.mutation.Encrypted(); !ok {
		return &ValidationError{Name: "encrypted", err: errors.New(`ent: missing required field "Share.encrypted"`)}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "Share.size"`)}
	}
	if _, ok := _c.mutation.BlobPath(); !ok {
		return &ValidationError{Name: "blob_path", err: errors.New(`ent: missing required field "Share.blob_path"`)}
	}
	if _, ok := _c.mutation.BlobSha256(); !ok {
		return &ValidationError{Name: "blob_sha256", err: errors.New(`ent: missing required field "Share.blob_sha256"`)}
	}
	if _, ok := _c.mutation.UploaderIP(); !ok {
		return &ValidationError{Name: "uploader_ip", err: errors.New(`ent: missing required field "Share.uploader_ip"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Share.created_at"`)}
	}
	return nil
}

func (_c *ShareCreate) sqlSave(ctx context.Context) (*Share, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Share.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShareCreate) createSpec() (*Share, *sqlgraph.CreateSpec) {
	var (
		_node = &Share{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(share.Table, sqlgraph.NewFieldSpec(share.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(share.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Visibility(); ok {
		_spec.SetField(share.FieldVisibility, field.TypeString, value)
		_node.Visibility = value
	}
	if value, ok := _c.mutation.PrivateKeyHash(); ok {
		_spec.SetField(share.FieldPrivateKeyHash, field.TypeString, value)
		_node.PrivateKeyHash = &value
	}
	if value, ok := _c.mutation.Encrypted(); ok {
		_spec.SetField(share.FieldEncrypted, field.TypeBool, value)
		_node.Encrypted = value
	}
	if value, ok := _c.mutation.CipherMeta(); ok {
		_spec.SetField(share.FieldCipherMeta, field.TypeString, value)
		_node.CipherMeta = value
	}
	if value, ok := _c.mutation.ZipManifest(); ok {
		_spec.SetField(share.FieldZipManifest, field.TypeString, value)
		_node.ZipManifest = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(share.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.BlobPath(); ok {
		_spec.SetField(share.FieldBlobPath, field.TypeString, value)
		_node.BlobPath = value
	}
	if value, ok := _c.mutation.BlobSha256(); ok {
		_spec.SetField(share.FieldBlobSha256, field.TypeString, value)
		_node.BlobSha256 = value
	}
	if value, ok := _c.mutation.UploaderIP(); ok {
		_spec.SetField(share.FieldUploaderIP, field.TypeString, value)
		_node.UploaderIP = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(share.FieldExpiresAt, field.TypeString, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(share.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.PurgedAt(); ok {
		_spec.SetField(share.FieldPurgedAt, field.TypeString, value)
		_node.PurgedAt = &value
	}
	return _node, _spec
}

// ShareCreateBulk is the builder for creating many Share entities in bulk.
type ShareCreateBulk struct {
	config
	err      error
	builders []*ShareCreate
}

// Save creates the Share entities in the database.
func (_c *ShareCreateBulk) Save(ctx context.Context) ([]*Share, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Share, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShareMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShareCreateBulk) SaveX(ctx context.Context) []*Share {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShareCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShareCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
