// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"shareserver/internal/ent/share"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Share is the model entity for the Share schema.
type Share struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Visibility holds the value of the "visibility" field.
	Visibility string `json:"visibility,omitempty"`
	// PrivateKeyHash holds the value of the "private_key_hash" field.
	PrivateKeyHash *string `json:"private_key_hash,omitempty"`
	// Encrypted holds the value of the "encrypted" field.
	Encrypted bool `json:"encrypted,omitempty"`
	// CipherMeta holds the value of the "cipher_meta" field.
	CipherMeta string `json:"cipher_meta,omitempty"`
	// ZipManifest holds the value of the "zip_manifest" field.
	ZipManifest string `json:"zip_manifest,omitempty"`
	// Size holds the value of the "size" field.
	Size int64 `json:"size,omitempty"`
	// BlobPath holds the value of the "blob_path" field.
	BlobPath string `json:"blob_path,omitempty"`
	// BlobSha256 holds the value of the "blob_sha256" field.
	BlobSha256 string `json:"blob_sha256,omitempty"`
	// UploaderIP holds the value of the "uploader_ip" field.
	UploaderIP string `json:"uploader_ip,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *string `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt string `json:"created_at,omitempty"`
	// PurgedAt holds the value of the "purged_at" field.
	PurgedAt     *string `json:"purged_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Share) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case share.FieldEncrypted:
			values[i] = new(sql.NullBool)
		case share.FieldSize:
			values[i] = new(sql.NullInt64)
		case share.FieldID, share.FieldTitle, share.FieldVisibility, share.FieldPrivateKeyHash, share.FieldCipherMeta, share.FieldZipManifest, share.FieldBlobPath, share.FieldBlobSha256, share.FieldUploaderIP, share.FieldExpiresAt, share.FieldCreatedAt, share.FieldPurgedAt:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Share fields.
func (_m *Share) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case share.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case share.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case share.FieldVisibility:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visibility", values[i])
			} else if value.Valid {
				_m.Visibility = value.String
			}
		case share.FieldPrivateKeyHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field private_key_hash", values[i])
			} else if value.Valid {
				_m.PrivateKeyHash = new(string)
				*_m.PrivateKeyHash = value.String
			}
		case share.FieldEncrypted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted", values[i])
			} else if value.Valid {
				_m.Encrypted = value.Bool
			}
		case share.FieldCipherMeta:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cipher_meta", values[i])
			} else if value.Valid {
				_m.CipherMeta = value.String
			}
		case share.FieldZipManifest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field zip_manifest", values[i])
			} else if value.Valid {
				_m.ZipManifest = value.String
			}
		case share.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = value.Int64
			}
		case share.FieldBlobPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field blob_path", values[i])
			} else if value.Valid {
				_m.BlobPath = value.String
			}
		case share.FieldBlobSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field blob_sha256", values[i])
			} else if value.Valid {
				_m.BlobSha256 = value.String
			}
		case share.FieldUploaderIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uploader_ip", values[i])
			} else if value.Valid {
				_m.UploaderIP = value.String
			}
		case share.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(string)
				*_m.ExpiresAt = value.String
			}
		case share.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.String
			}
		case share.FieldPurgedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field purged_at", values[i])
			} else if value.Valid {
				_m.PurgedAt = new(string)
				*_m.PurgedAt = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Share.
// This includes values selected through modifiers, order, etc.
func (_m *Share) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Share.
// Note that you need to call Share.Unwrap() before calling this method if this Share
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Share) Update() *ShareUpdateOne {
	return NewShareClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Share entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Share) Unwrap() *Share {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Share is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Share) String() string {
	var builder strings.Builder
	builder.WriteString("Share(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("visibility=")
	builder.WriteString(_m.Visibility)
	builder.WriteString(", ")
	if v := _m.PrivateKeyHash; v != nil {
		builder.WriteString("private_key_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("encrypted=")
	builder.WriteString(fmt.Sprintf("%v", _m.Encrypted))
	builder.WriteString(", ")
	builder.WriteString("cipher_meta=")
	builder.WriteString(_m.CipherMeta)
	builder.WriteString(", ")
	builder.WriteString("zip_manifest=")
	builder.WriteString(_m.ZipManifest)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", _m.Size))
	builder.WriteString(", ")
	builder.WriteString("blob_path=")
	builder.WriteString(_m.BlobPath)
	builder.WriteString(", ")
	builder.WriteString("blob_sha256=")
	builder.WriteString(_m.BlobSha256)
	builder.WriteString(", ")
	builder.WriteString("uploader_ip=")
	builder.WriteString(_m.UploaderIP)
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt)
	builder.WriteString(", ")
	if v := _m.PurgedAt; v != nil {
		builder.WriteString("purged_at=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Shares is a parsable slice of Share.
type Shares []*Share
