// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Admin is the predicate function for admin builders.
type Admin func(*sql.Selector)

// AuditEvent is the predicate function for auditevent builders.
type AuditEvent func(*sql.Selector)

// IpBan is the predicate function for ipban builders.
type IpBan func(*sql.Selector)

// LoginFailureEvent is the predicate function for loginfailureevent builders.
type LoginFailureEvent func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Share is the predicate function for share builders.
type Share func(*sql.Selector)
