// Code generated by ent, DO NOT EDIT.

package loginfailureevent

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the loginfailureevent type in the database.
	Label = "login_failure_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldHappenedAt holds the string denoting the happened_at field in the database.
	FieldHappenedAt = "happened_at"
	// Table holds the table name of the loginfailureevent in the database.
	Table = "login_failure_events"
)

// Columns holds all SQL columns for loginfailureevent fields.
var Columns = []string{
	FieldID,
	FieldIP,
	FieldHappenedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the LoginFailureEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIP orders the results by the ip field.
func ByIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIP, opts...).ToFunc()
}

// ByHappenedAt orders the results by the happened_at field.
func ByHappenedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHappenedAt, opts...).ToFunc()
}
