// Code generated by ent, DO NOT EDIT.

package loginfailureevent

import (
	"shareserver/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldLTE(FieldID, id))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldEQ(FieldIP, v))
}

// HappenedAt applies equality check predicate on the "happened_at" field. It's identical to HappenedAtEQ.
func HappenedAt(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldEQ(FieldHappenedAt, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldContainsFold(FieldIP, v))
}

// HappenedAtEQ applies the EQ predicate on the "happened_at" field.
func HappenedAtEQ(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldEQ(FieldHappenedAt, v))
}

// HappenedAtNEQ applies the NEQ predicate on the "happened_at" field.
func HappenedAtNEQ(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldNEQ(FieldHappenedAt, v))
}

// HappenedAtIn applies the In predicate on the "happened_at" field.
func HappenedAtIn(vs ...string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldIn(FieldHappenedAt, vs...))
}

// HappenedAtNotIn applies the NotIn predicate on the "happened_at" field.
func HappenedAtNotIn(vs ...string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldNotIn(FieldHappenedAt, vs...))
}

// HappenedAtGT applies the GT predicate on the "happened_at" field.
func HappenedAtGT(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldGT(FieldHappenedAt, v))
}

// HappenedAtGTE applies the GTE predicate on the "happened_at" field.
func HappenedAtGTE(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldGTE(FieldHappenedAt, v))
}

// HappenedAtLT applies the LT predicate on the "happened_at" field.
func HappenedAtLT(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldLT(FieldHappenedAt, v))
}

// HappenedAtLTE applies the LTE predicate on the "happened_at" field.
func HappenedAtLTE(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldLTE(FieldHappenedAt, v))
}

// HappenedAtContains applies the Contains predicate on the "happened_at" field.
func HappenedAtContains(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldContains(FieldHappenedAt, v))
}

// HappenedAtHasPrefix applies the HasPrefix predicate on the "happened_at" field.
func HappenedAtHasPrefix(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldHasPrefix(FieldHappenedAt, v))
}

// HappenedAtHasSuffix applies the HasSuffix predicate on the "happened_at" field.
func HappenedAtHasSuffix(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldHasSuffix(FieldHappenedAt, v))
}

// HappenedAtEqualFold applies the EqualFold predicate on the "happened_at" field.
func HappenedAtEqualFold(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldEqualFold(FieldHappenedAt, v))
}

// HappenedAtContainsFold applies the ContainsFold predicate on the "happened_at" field.
func HappenedAtContainsFold(v string) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.FieldContainsFold(FieldHappenedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LoginFailureEvent) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LoginFailureEvent) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LoginFailureEvent) predicate.LoginFailureEvent {
	return predicate.LoginFailureEvent(sql.NotPredicates(p))
}
