// Code generated by ent, DO NOT EDIT.

package ipban

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the ipban type in the database.
	Label = "ip_ban"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "ip"
	// FieldBannedUntil holds the string denoting the banned_until field in the database.
	FieldBannedUntil = "banned_until"
	// Table holds the table name of the ipban in the database.
	Table = "ip_bans"
)

// Columns holds all SQL columns for ipban fields.
var Columns = []string{
	FieldID,
	FieldBannedUntil,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the IpBan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBannedUntil orders the results by the banned_until field.
func ByBannedUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBannedUntil, opts...).ToFunc()
}
