// Code generated by ent, DO NOT EDIT.

package ipban

import (
	"shareserver/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.IpBan {
	return predicate.IpBan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.IpBan {
	return predicate.IpBan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.IpBan {
	return predicate.IpBan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.IpBan {
	return predicate.IpBan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.IpBan {
	return predicate.IpBan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.IpBan {
	return predicate.IpBan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.IpBan {
	return predicate.IpBan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.IpBan {
	return predicate.IpBan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.IpBan {
	return predicate.IpBan(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.IpBan {
	return predicate.IpBan(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.IpBan {
	return predicate.IpBan(sql.FieldContainsFold(FieldID, id))
}

// BannedUntil applies equality check predicate on the "banned_until" field. It's identical to BannedUntilEQ.
func BannedUntil(v string) predicate.IpBan {
	return predicate.IpBan(sql.FieldEQ(FieldBannedUntil, v))
}

// BannedUntilEQ applies the EQ predicate on the "banned_until" field.
func BannedUntilEQ(v string) predicate.IpBan {
	return predicate.IpBan(sql.FieldEQ(FieldBannedUntil, v))
}

// BannedUntilNEQ applies the NEQ predicate on the "banned_until" field.
func BannedUntilNEQ(v string) predicate.IpBan {
	return predicate.IpBan(sql.FieldNEQ(FieldBannedUntil, v))
}

// BannedUntilIn applies the In predicate on the "banned_until" field.
func BannedUntilIn(vs ...string) predicate.IpBan {
	return predicate.IpBan(sql.FieldIn(FieldBannedUntil, vs...))
}

// BannedUntilNotIn applies the NotIn predicate on the "banned_until" field.
func BannedUntilNotIn(vs ...string) predicate.IpBan {
	return predicate.IpBan(sql.FieldNotIn(FieldBannedUntil, vs...))
}

// BannedUntilGT applies the GT predicate on the "banned_until" field.
func BannedUntilGT(v string) predicate.IpBan {
	return predicate.IpBan(sql.FieldGT(FieldBannedUntil, v))
}

// BannedUntilGTE applies the GTE predicate on the "banned_until" field.
func BannedUntilGTE(v string) predicate.IpBan {
	return predicate.IpBan(sql.FieldGTE(FieldBannedUntil, v))
}

// BannedUntilLT applies the LT predicate on the "banned_until" field.
func BannedUntilLT(v string) predicate.IpBan {
	return predicate.IpBan(sql.FieldLT(FieldBannedUntil, v))
}

// BannedUntilLTE applies the LTE predicate on the "banned_until" field.
func BannedUntilLTE(v string) predicate.IpBan {
	return predicate.IpBan(sql.FieldLTE(FieldBannedUntil, v))
}

// BannedUntilContains applies the Contains predicate on the "banned_until" field.
func BannedUntilContains(v string) predicate.IpBan {
	return predicate.IpBan(sql.FieldContains(FieldBannedUntil, v))
}

// BannedUntilHasPrefix applies the HasPrefix predicate on the "banned_until" field.
func BannedUntilHasPrefix(v string) predicate.IpBan {
	return predicate.IpBan(sql.FieldHasPrefix(FieldBannedUntil, v))
}

// BannedUntilHasSuffix applies the HasSuffix predicate on the "banned_until" field.
func BannedUntilHasSuffix(v string) predicate.IpBan {
	return predicate.IpBan(sql.FieldHasSuffix(FieldBannedUntil, v))
}

// BannedUntilEqualFold applies the EqualFold predicate on the "banned_until" field.
func BannedUntilEqualFold(v string) predicate.IpBan {
	return predicate.IpBan(sql.FieldEqualFold(FieldBannedUntil, v))
}

// BannedUntilContainsFold applies the ContainsFold predicate on the "banned_until" field.
func BannedUntilContainsFold(v string) predicate.IpBan {
	return predicate.IpBan(sql.FieldContainsFold(FieldBannedUntil, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IpBan) predicate.IpBan {
	return predicate.IpBan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IpBan) predicate.IpBan {
	return predicate.IpBan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IpBan) predicate.IpBan {
	return predicate.IpBan(sql.NotPredicates(p))
}
