// Code generated by ent, DO NOT EDIT.

package share

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the share type in the database.
	Label = "share"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldVisibility holds the string denoting the visibility field in the database.
	FieldVisibility = "visibility"
	// FieldPrivateKeyHash holds the string denoting the private_key_hash field in the database.
	FieldPrivateKeyHash = "private_key_hash"
	// FieldEncrypted holds the string denoting the encrypted field in the database.
	FieldEncrypted = "encrypted"
	// FieldCipherMeta holds the string denoting the cipher_meta field in the database.
	FieldCipherMeta = "cipher_meta"
	// FieldZipManifest holds the string denoting the zip_manifest field in the database.
	FieldZipManifest = "zip_manifest"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldBlobPath holds the string denoting the blob_path field in the database.
	FieldBlobPath = "blob_path"
	// FieldBlobSha256 holds the string denoting the blob_sha256 field in the database.
	FieldBlobSha256 = "blob_sha256"
	// FieldUploaderIP holds the string denoting the uploader_ip field in the database.
	FieldUploaderIP = "uploader_ip"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldPurgedAt holds the string denoting the purged_at field in the database.
	FieldPurgedAt = "purged_at"
	// Table holds the table name of the share in the database.
	Table = "shares"
)

// Columns holds all SQL columns for share fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldVisibility,
	FieldPrivateKeyHash,
	FieldEncrypted,
	FieldCipherMeta,
	FieldZipManifest,
	FieldSize,
	FieldBlobPath,
	FieldBlobSha256,
	FieldUploaderIP,
	FieldExpiresAt,
	FieldCreatedAt,
	FieldPurgedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Share queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByVisibility orders the results by the visibility field.
func ByVisibility(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVisibility, opts...).ToFunc()
}

// ByPrivateKeyHash orders the results by the private_key_hash field.
func ByPrivateKeyHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrivateKeyHash, opts...).ToFunc()
}

// ByEncrypted orders the results by the encrypted field.
func ByEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncrypted, opts...).ToFunc()
}

// ByCipherMeta orders the results by the cipher_meta field.
func ByCipherMeta(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCipherMeta, opts...).ToFunc()
}

// ByZipManifest orders the results by the zip_manifest field.
func ByZipManifest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldZipManifest, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByBlobPath orders the results by the blob_path field.
func ByBlobPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlobPath, opts...).ToFunc()
}

// ByBlobSha256 orders the results by the blob_sha256 field.
func ByBlobSha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlobSha256, opts...).ToFunc()
}

// ByUploaderIP orders the results by the uploader_ip field.
func ByUploaderIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploaderIP, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByPurgedAt orders the results by the purged_at field.
func ByPurgedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurgedAt, opts...).ToFunc()
}
