// Code generated by ent, DO NOT EDIT.

package share

import (
	"shareserver/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldTitle, v))
}

// Visibility applies equality check predicate on the "visibility" field. It's identical to VisibilityEQ.
func Visibility(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldVisibility, v))
}

// PrivateKeyHash applies equality check predicate on the "private_key_hash" field. It's identical to PrivateKeyHashEQ.
func PrivateKeyHash(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldPrivateKeyHash, v))
}

// Encrypted applies equality check predicate on the "encrypted" field. It's identical to EncryptedEQ.
func Encrypted(v bool) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldEncrypted, v))
}

// CipherMeta applies equality check predicate on the "cipher_meta" field. It's identical to CipherMetaEQ.
func CipherMeta(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldCipherMeta, v))
}

// ZipManifest applies equality check predicate on the "zip_manifest" field. It's identical to ZipManifestEQ.
func ZipManifest(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldZipManifest, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldSize, v))
}

// BlobPath applies equality check predicate on the "blob_path" field. It's identical to BlobPathEQ.
func BlobPath(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldBlobPath, v))
}

// BlobSha256 applies equality check predicate on the "blob_sha256" field. It's identical to BlobSha256EQ.
func BlobSha256(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldBlobSha256, v))
}

// UploaderIP applies equality check predicate on the "uploader_ip" field. It's identical to UploaderIPEQ.
func UploaderIP(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldUploaderIP, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldCreatedAt, v))
}

// PurgedAt applies equality check predicate on the "purged_at" field. It's identical to PurgedAtEQ.
func PurgedAt(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldPurgedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldTitle, v))
}

// VisibilityEQ applies the EQ predicate on the "visibility" field.
func VisibilityEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldVisibility, v))
}

// VisibilityNEQ applies the NEQ predicate on the "visibility" field.
func VisibilityNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldVisibility, v))
}

// VisibilityIn applies the In predicate on the "visibility" field.
func VisibilityIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldVisibility, vs...))
}

// VisibilityNotIn applies the NotIn predicate on the "visibility" field.
func VisibilityNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldVisibility, vs...))
}

// VisibilityGT applies the GT predicate on the "visibility" field.
func VisibilityGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldVisibility, v))
}

// VisibilityGTE applies the GTE predicate on the "visibility" field.
func VisibilityGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldVisibility, v))
}

// VisibilityLT applies the LT predicate on the "visibility" field.
func VisibilityLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldVisibility, v))
}

// VisibilityLTE applies the LTE predicate on the "visibility" field.
func VisibilityLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldVisibility, v))
}

// VisibilityContains applies the Contains predicate on the "visibility" field.
func VisibilityContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldVisibility, v))
}

// VisibilityHasPrefix applies the HasPrefix predicate on the "visibility" field.
func VisibilityHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldVisibility, v))
}

// VisibilityHasSuffix applies the HasSuffix predicate on the "visibility" field.
func VisibilityHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldVisibility, v))
}

// VisibilityEqualFold applies the EqualFold predicate on the "visibility" field.
func VisibilityEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldVisibility, v))
}

// VisibilityContainsFold applies the ContainsFold predicate on the "visibility" field.
func VisibilityContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldVisibility, v))
}

// PrivateKeyHashEQ applies the EQ predicate on the "private_key_hash" field.
func PrivateKeyHashEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldPrivateKeyHash, v))
}

// PrivateKeyHashNEQ applies the NEQ predicate on the "private_key_hash" field.
func PrivateKeyHashNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldPrivateKeyHash, v))
}

// PrivateKeyHashIn applies the In predicate on the "private_key_hash" field.
func PrivateKeyHashIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldPrivateKeyHash, vs...))
}

// PrivateKeyHashNotIn applies the NotIn predicate on the "private_key_hash" field.
func PrivateKeyHashNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldPrivateKeyHash, vs...))
}

// PrivateKeyHashGT applies the GT predicate on the "private_key_hash" field.
func PrivateKeyHashGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldPrivateKeyHash, v))
}

// PrivateKeyHashGTE applies the GTE predicate on the "private_key_hash" field.
func PrivateKeyHashGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldPrivateKeyHash, v))
}

// PrivateKeyHashLT applies the LT predicate on the "private_key_hash" field.
func PrivateKeyHashLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldPrivateKeyHash, v))
}

// PrivateKeyHashLTE applies the LTE predicate on the "private_key_hash" field.
func PrivateKeyHashLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldPrivateKeyHash, v))
}

// PrivateKeyHashContains applies the Contains predicate on the "private_key_hash" field.
func PrivateKeyHashContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldPrivateKeyHash, v))
}

// PrivateKeyHashHasPrefix applies the HasPrefix predicate on the "private_key_hash" field.
func PrivateKeyHashHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldPrivateKeyHash, v))
}

// PrivateKeyHashHasSuffix applies the HasSuffix predicate on the "private_key_hash" field.
func PrivateKeyHashHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldPrivateKeyHash, v))
}

// PrivateKeyHashIsNil applies the IsNil predicate on the "private_key_hash" field.
func PrivateKeyHashIsNil() predicate.Share {
	return predicate.Share(sql.FieldIsNull(FieldPrivateKeyHash))
}

// PrivateKeyHashNotNil applies the NotNil predicate on the "private_key_hash" field.
func PrivateKeyHashNotNil() predicate.Share {
	return predicate.Share(sql.FieldNotNull(FieldPrivateKeyHash))
}

// PrivateKeyHashEqualFold applies the EqualFold predicate on the "private_key_hash" field.
func PrivateKeyHashEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldPrivateKeyHash, v))
}

// PrivateKeyHashContainsFold applies the ContainsFold predicate on the "private_key_hash" field.
func PrivateKeyHashContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldPrivateKeyHash, v))
}

// EncryptedEQ applies the EQ predicate on the "encrypted" field.
func EncryptedEQ(v bool) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldEncrypted, v))
}

// EncryptedNEQ applies the NEQ predicate on the "encrypted" field.
func EncryptedNEQ(v bool) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldEncrypted, v))
}

// CipherMetaEQ applies the EQ predicate on the "cipher_meta" field.
func CipherMetaEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldCipherMeta, v))
}

// CipherMetaNEQ applies the NEQ predicate on the "cipher_meta" field.
func CipherMetaNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldCipherMeta, v))
}

// CipherMetaIn applies the In predicate on the "cipher_meta" field.
func CipherMetaIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldCipherMeta, vs...))
}

// CipherMetaNotIn applies the NotIn predicate on the "cipher_meta" field.
func CipherMetaNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldCipherMeta, vs...))
}

// CipherMetaGT applies the GT predicate on the "cipher_meta" field.
func CipherMetaGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldCipherMeta, v))
}

// CipherMetaGTE applies the GTE predicate on the "cipher_meta" field.
func CipherMetaGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldCipherMeta, v))
}

// CipherMetaLT applies the LT predicate on the "cipher_meta" field.
func CipherMetaLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldCipherMeta, v))
}

// CipherMetaLTE applies the LTE predicate on the "cipher_meta" field.
func CipherMetaLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldCipherMeta, v))
}

// CipherMetaContains applies the Contains predicate on the "cipher_meta" field.
func CipherMetaContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldCipherMeta, v))
}

// CipherMetaHasPrefix applies the HasPrefix predicate on the "cipher_meta" field.
func CipherMetaHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldCipherMeta, v))
}

// CipherMetaHasSuffix applies the HasSuffix predicate on the "cipher_meta" field.
func CipherMetaHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldCipherMeta, v))
}

// CipherMetaIsNil applies the IsNil predicate on the "cipher_meta" field.
func CipherMetaIsNil() predicate.Share {
	return predicate.Share(sql.FieldIsNull(FieldCipherMeta))
}

// CipherMetaNotNil applies the NotNil predicate on the "cipher_meta" field.
func CipherMetaNotNil() predicate.Share {
	return predicate.Share(sql.FieldNotNull(FieldCipherMeta))
}

// CipherMetaEqualFold applies the EqualFold predicate on the "cipher_meta" field.
func CipherMetaEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldCipherMeta, v))
}

// CipherMetaContainsFold applies the ContainsFold predicate on the "cipher_meta" field.
func CipherMetaContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldCipherMeta, v))
}

// ZipManifestEQ applies the EQ predicate on the "zip_manifest" field.
func ZipManifestEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldZipManifest, v))
}

// ZipManifestNEQ applies the NEQ predicate on the "zip_manifest" field.
func ZipManifestNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldZipManifest, v))
}

// ZipManifestIn applies the In predicate on the "zip_manifest" field.
func ZipManifestIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldZipManifest, vs...))
}

// ZipManifestNotIn applies the NotIn predicate on the "zip_manifest" field.
func ZipManifestNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldZipManifest, vs...))
}

// ZipManifestGT applies the GT predicate on the "zip_manifest" field.
func ZipManifestGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldZipManifest, v))
}

// ZipManifestGTE applies the GTE predicate on the "zip_manifest" field.
func ZipManifestGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldZipManifest, v))
}

// ZipManifestLT applies the LT predicate on the "zip_manifest" field.
func ZipManifestLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldZipManifest, v))
}

// ZipManifestLTE applies the LTE predicate on the "zip_manifest" field.
func ZipManifestLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldZipManifest, v))
}

// ZipManifestContains applies the Contains predicate on the "zip_manifest" field.
func ZipManifestContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldZipManifest, v))
}

// ZipManifestHasPrefix applies the HasPrefix predicate on the "zip_manifest" field.
func ZipManifestHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldZipManifest, v))
}

// ZipManifestHasSuffix applies the HasSuffix predicate on the "zip_manifest" field.
func ZipManifestHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldZipManifest, v))
}

// ZipManifestIsNil applies the IsNil predicate on the "zip_manifest" field.
func ZipManifestIsNil() predicate.Share {
	return predicate.Share(sql.FieldIsNull(FieldZipManifest))
}

// ZipManifestNotNil applies the NotNil predicate on the "zip_manifest" field.
func ZipManifestNotNil() predicate.Share {
	return predicate.Share(sql.FieldNotNull(FieldZipManifest))
}

// ZipManifestEqualFold applies the EqualFold predicate on the "zip_manifest" field.
func ZipManifestEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldZipManifest, v))
}

// ZipManifestContainsFold applies the ContainsFold predicate on the "zip_manifest" field.
func ZipManifestContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldZipManifest, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldSize, v))
}

// BlobPathEQ applies the EQ predicate on the "blob_path" field.
func BlobPathEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldBlobPath, v))
}

// BlobPathNEQ applies the NEQ predicate on the "blob_path" field.
func BlobPathNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldBlobPath, v))
}

// BlobPathIn applies the In predicate on the "blob_path" field.
func BlobPathIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldBlobPath, vs...))
}

// BlobPathNotIn applies the NotIn predicate on the "blob_path" field.
func BlobPathNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldBlobPath, vs...))
}

// BlobPathGT applies the GT predicate on the "blob_path" field.
func BlobPathGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldBlobPath, v))
}

// BlobPathGTE applies the GTE predicate on the "blob_path" field.
func BlobPathGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldBlobPath, v))
}

// BlobPathLT applies the LT predicate on the "blob_path" field.
func BlobPathLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldBlobPath, v))
}

// BlobPathLTE applies the LTE predicate on the "blob_path" field.
func BlobPathLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldBlobPath, v))
}

// BlobPathContains applies the Contains predicate on the "blob_path" field.
func BlobPathContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldBlobPath, v))
}

// BlobPathHasPrefix applies the HasPrefix predicate on the "blob_path" field.
func BlobPathHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldBlobPath, v))
}

// BlobPathHasSuffix applies the HasSuffix predicate on the "blob_path" field.
func BlobPathHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldBlobPath, v))
}

// BlobPathEqualFold applies the EqualFold predicate on the "blob_path" field.
func BlobPathEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldBlobPath, v))
}

// BlobPathContainsFold applies the ContainsFold predicate on the "blob_path" field.
func BlobPathContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldBlobPath, v))
}

// BlobSha256EQ applies the EQ predicate on the "blob_sha256" field.
func BlobSha256EQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldBlobSha256, v))
}

// BlobSha256NEQ applies the NEQ predicate on the "blob_sha256" field.
func BlobSha256NEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldBlobSha256, v))
}

// BlobSha256In applies the In predicate on the "blob_sha256" field.
func BlobSha256In(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldBlobSha256, vs...))
}

// BlobSha256NotIn applies the NotIn predicate on the "blob_sha256" field.
func BlobSha256NotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldBlobSha256, vs...))
}

// BlobSha256GT applies the GT predicate on the "blob_sha256" field.
func BlobSha256GT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldBlobSha256, v))
}

// BlobSha256GTE applies the GTE predicate on the "blob_sha256" field.
func BlobSha256GTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldBlobSha256, v))
}

// BlobSha256LT applies the LT predicate on the "blob_sha256" field.
func BlobSha256LT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldBlobSha256, v))
}

// BlobSha256LTE applies the LTE predicate on the "blob_sha256" field.
func BlobSha256LTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldBlobSha256, v))
}

// BlobSha256Contains applies the Contains predicate on the "blob_sha256" field.
func BlobSha256Contains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldBlobSha256, v))
}

// BlobSha256HasPrefix applies the HasPrefix predicate on the "blob_sha256" field.
func BlobSha256HasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldBlobSha256, v))
}

// BlobSha256HasSuffix applies the HasSuffix predicate on the "blob_sha256" field.
func BlobSha256HasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldBlobSha256, v))
}

// BlobSha256EqualFold applies the EqualFold predicate on the "blob_sha256" field.
func BlobSha256EqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldBlobSha256, v))
}

// BlobSha256ContainsFold applies the ContainsFold predicate on the "blob_sha256" field.
func BlobSha256ContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldBlobSha256, v))
}

// UploaderIPEQ applies the EQ predicate on the "uploader_ip" field.
func UploaderIPEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldUploaderIP, v))
}

// UploaderIPNEQ applies the NEQ predicate on the "uploader_ip" field.
func UploaderIPNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldUploaderIP, v))
}

// UploaderIPIn applies the In predicate on the "uploader_ip" field.
func UploaderIPIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldUploaderIP, vs...))
}

// UploaderIPNotIn applies the NotIn predicate on the "uploader_ip" field.
func UploaderIPNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldUploaderIP, vs...))
}

// UploaderIPGT applies the GT predicate on the "uploader_ip" field.
func UploaderIPGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldUploaderIP, v))
}

// UploaderIPGTE applies the GTE predicate on the "uploader_ip" field.
func UploaderIPGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldUploaderIP, v))
}

// UploaderIPLT applies the LT predicate on the "uploader_ip" field.
func UploaderIPLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldUploaderIP, v))
}

// UploaderIPLTE applies the LTE predicate on the "uploader_ip" field.
func UploaderIPLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldUploaderIP, v))
}

// UploaderIPContains applies the Contains predicate on the "uploader_ip" field.
func UploaderIPContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldUploaderIP, v))
}

// UploaderIPHasPrefix applies the HasPrefix predicate on the "uploader_ip" field.
func UploaderIPHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldUploaderIP, v))
}

// UploaderIPHasSuffix applies the HasSuffix predicate on the "uploader_ip" field.
func UploaderIPHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldUploaderIP, v))
}

// UploaderIPEqualFold applies the EqualFold predicate on the "uploader_ip" field.
func UploaderIPEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldUploaderIP, v))
}

// UploaderIPContainsFold applies the ContainsFold predicate on the "uploader_ip" field.
func UploaderIPContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldUploaderIP, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtContains applies the Contains predicate on the "expires_at" field.
func ExpiresAtContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldExpiresAt, v))
}

// ExpiresAtHasPrefix applies the HasPrefix predicate on the "expires_at" field.
func ExpiresAtHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldExpiresAt, v))
}

// ExpiresAtHasSuffix applies the HasSuffix predicate on the "expires_at" field.
func ExpiresAtHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.Share {
	return predicate.Share(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.Share {
	return predicate.Share(sql.FieldNotNull(FieldExpiresAt))
}

// ExpiresAtEqualFold applies the EqualFold predicate on the "expires_at" field.
func ExpiresAtEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldExpiresAt, v))
}

// ExpiresAtContainsFold applies the ContainsFold predicate on the "expires_at" field.
func ExpiresAtContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtContains applies the Contains predicate on the "created_at" field.
func CreatedAtContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldCreatedAt, v))
}

// CreatedAtHasPrefix applies the HasPrefix predicate on the "created_at" field.
func CreatedAtHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldCreatedAt, v))
}

// CreatedAtHasSuffix applies the HasSuffix predicate on the "created_at" field.
func CreatedAtHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldCreatedAt, v))
}

// CreatedAtEqualFold applies the EqualFold predicate on the "created_at" field.
func CreatedAtEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldCreatedAt, v))
}

// CreatedAtContainsFold applies the ContainsFold predicate on the "created_at" field.
func CreatedAtContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldCreatedAt, v))
}

// PurgedAtEQ applies the EQ predicate on the "purged_at" field.
func PurgedAtEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldEQ(FieldPurgedAt, v))
}

// PurgedAtNEQ applies the NEQ predicate on the "purged_at" field.
func PurgedAtNEQ(v string) predicate.Share {
	return predicate.Share(sql.FieldNEQ(FieldPurgedAt, v))
}

// PurgedAtIn applies the In predicate on the "purged_at" field.
func PurgedAtIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldIn(FieldPurgedAt, vs...))
}

// PurgedAtNotIn applies the NotIn predicate on the "purged_at" field.
func PurgedAtNotIn(vs ...string) predicate.Share {
	return predicate.Share(sql.FieldNotIn(FieldPurgedAt, vs...))
}

// PurgedAtGT applies the GT predicate on the "purged_at" field.
func PurgedAtGT(v string) predicate.Share {
	return predicate.Share(sql.FieldGT(FieldPurgedAt, v))
}

// PurgedAtGTE applies the GTE predicate on the "purged_at" field.
func PurgedAtGTE(v string) predicate.Share {
	return predicate.Share(sql.FieldGTE(FieldPurgedAt, v))
}

// PurgedAtLT applies the LT predicate on the "purged_at" field.
func PurgedAtLT(v string) predicate.Share {
	return predicate.Share(sql.FieldLT(FieldPurgedAt, v))
}

// PurgedAtLTE applies the LTE predicate on the "purged_at" field.
func PurgedAtLTE(v string) predicate.Share {
	return predicate.Share(sql.FieldLTE(FieldPurgedAt, v))
}

// PurgedAtContains applies the Contains predicate on the "purged_at" field.
func PurgedAtContains(v string) predicate.Share {
	return predicate.Share(sql.FieldContains(FieldPurgedAt, v))
}

// PurgedAtHasPrefix applies the HasPrefix predicate on the "purged_at" field.
func PurgedAtHasPrefix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasPrefix(FieldPurgedAt, v))
}

// PurgedAtHasSuffix applies the HasSuffix predicate on the "purged_at" field.
func PurgedAtHasSuffix(v string) predicate.Share {
	return predicate.Share(sql.FieldHasSuffix(FieldPurgedAt, v))
}

// PurgedAtIsNil applies the IsNil predicate on the "purged_at" field.
func PurgedAtIsNil() predicate.Share {
	return predicate.Share(sql.FieldIsNull(FieldPurgedAt))
}

// PurgedAtNotNil applies the NotNil predicate on the "purged_at" field.
func PurgedAtNotNil() predicate.Share {
	return predicate.Share(sql.FieldNotNull(FieldPurgedAt))
}

// PurgedAtEqualFold applies the EqualFold predicate on the "purged_at" field.
func PurgedAtEqualFold(v string) predicate.Share {
	return predicate.Share(sql.FieldEqualFold(FieldPurgedAt, v))
}

// PurgedAtContainsFold applies the ContainsFold predicate on the "purged_at" field.
func PurgedAtContainsFold(v string) predicate.Share {
	return predicate.Share(sql.FieldContainsFold(FieldPurgedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Share) predicate.Share {
	return predicate.Share(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Share) predicate.Share {
	return predicate.Share(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Share) predicate.Share {
	return predicate.Share(sql.NotPredicates(p))
}
